---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: jupyter-tensorflow-ubi9-python-3-9-
commonLabels:
  app: jupyter-tensorflow-ubi9-python-3-9
resources:
  - service.yaml
  - statefulset.yaml
images:
  - name: quay.io/opendatahub/notebooks
    newName: quay.io/opendatahub/notebooks
    newTag: cuda-jupyter-tensorflow-ubi9-python-3.9
